---
apiVersion: apps/v1
kind: Service
metadata:
  name: nginx
  namespace: anjali-training
  labels:
    role: nginx
spec:
  loadBalancerSourceRanges:
  - 209.251.145.16/30
  - 34.68.218.96/32
  selector:
    role: nginx
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    protocol: TCP
    targetPort: http
