# Give staging smaller resources than production.# We created a macro that will output the above
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: anjali-training
  labels:
    role: php
spec:
  replicas: 1
  selector:
    matchLabels:
      role: php
  template:
    metadata:
      labels:
        role: php
    spec:
      containers:
      - name: php
        image: us.gcr.io/sharpspring-us/anjali-weatherapp:ffcd282
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "100Mi"

# vim:ft=ansible:
